const UserController = require('../controllers/user.controller');
const BookController = require('../controllers/book.controller');
const ReviewController = require('../controllers/review.controller');
const DriveController = require('../controllers/drive.controller');
const AuthController= require('../controllers/auth.controller')
const PointPackageController = require('../controllers/pointPackage.controller');
const MembershipPackageController = require('../controllers/membershipPackage.controller');
const PaymentController = require('../controllers/payment.controller');
module.exports={UserController, BookController, ReviewController, DriveController, AuthController, PointPackageController, MembershipPackageController, PaymentController};